spring:
  application:
    name: web
  thymeleaf:
    cache: false
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: hangang
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hangang.web
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.hangang.web: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: TRACE