-- 한강웹 전체 도메인 스키마
-- H2(로컬/테스트)·PostgreSQL 양쪽에서 동작하는 표준 SQL로 작성

-- 업체 (회원). 가입 시 status='PENDING', 관리자 승인 후 'APPROVED'.
CREATE TABLE IF NOT EXISTS vendor (
    vendor_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_name    VARCHAR(100) NOT NULL,
    business_reg_no  VARCHAR(20)  NOT NULL,
    ceo_name         VARCHAR(50)  NOT NULL,
    phone            VARCHAR(20)  NOT NULL,
    email            VARCHAR(100) NOT NULL UNIQUE,
    password         VARCHAR(100) NOT NULL,
    status           VARCHAR(20)  NOT NULL DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    created_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at      TIMESTAMP
);

-- 관리자. 업체 가입 승인/거부만 수행하며 계정은 직접 시딩한다(자체 가입 화면 없음).
CREATE TABLE IF NOT EXISTS admin (
    admin_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username     VARCHAR(50)  NOT NULL UNIQUE,
    password     VARCHAR(100) NOT NULL,
    created_at   TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 활동. 업체가 등록하면 관리자 검수 없이 즉시 노출된다.
-- daily_capacity: 활동 기간 중 하루당 정원(모든 날짜에 동일 적용).
CREATE TABLE IF NOT EXISTS activity (
    activity_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendor_id                BIGINT       NOT NULL REFERENCES vendor(vendor_id),
    title                    VARCHAR(200) NOT NULL,
    description              TEXT,
    location                 VARCHAR(200),
    image_path               VARCHAR(500),
    price                    INTEGER      NOT NULL,
    registration_start_date  DATE         NOT NULL, -- 신청 등록 기간 시작
    registration_end_date    DATE         NOT NULL, -- 신청 등록 기간 종료
    activity_start_date      DATE         NOT NULL, -- 활동 진행 기간 시작 (신청자가 이 범위 중 하루를 선택)
    activity_end_date        DATE         NOT NULL, -- 활동 진행 기간 종료
    daily_capacity           INTEGER      NOT NULL,
    status                   VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE', -- ACTIVE, CLOSED
    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 기존에 생성된 activity 테이블에도 안전하게 컬럼을 추가한다 (신규 설치 시에는 위 CREATE TABLE에서 이미 포함됨).
ALTER TABLE activity ADD COLUMN IF NOT EXISTS image_path VARCHAR(500);

-- 참여 신청 (비회원). 정원 초과분은 별도 상태 없이 status='PENDING'인 채로 대기열을 구성하며,
-- 업체가 날짜별 정원 내에서 원하는 신청자를 선택해 'APPROVED'로 변경한다.
-- token: 문자/이메일로 전달되는 영구 조회 링크用 고유 토큰 (로그인 대체).
CREATE TABLE IF NOT EXISTS application (
    application_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id           BIGINT       NOT NULL REFERENCES activity(activity_id),
    applicant_name         VARCHAR(50)  NOT NULL,
    phone                  VARCHAR(20)  NOT NULL,
    email                  VARCHAR(100) NOT NULL,
    gender                 VARCHAR(10)  NOT NULL,
    participation_date     DATE         NOT NULL, -- activity 기간 중 신청자가 선택한 하루
    status                 VARCHAR(20)  NOT NULL DEFAULT 'PENDING', -- PENDING(대기), APPROVED(승인), CANCELLED(취소)
    token                  VARCHAR(36)  NOT NULL UNIQUE,
    created_at             TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    approved_at            TIMESTAMP,
    cancelled_at           TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_activity_vendor ON activity(vendor_id);
CREATE INDEX IF NOT EXISTS idx_application_activity_date ON application(activity_id, participation_date);
CREATE INDEX IF NOT EXISTS idx_application_token ON application(token);

-- 공지사항. 관리자가 작성/수정하며 삭제는 없고 숨김 처리만 가능.
-- publish_date: 이 날짜부터 공개 노출(예약 게시). hidden: 관리자가 수동으로 노출을 끈 상태.
CREATE TABLE IF NOT EXISTS notice (
    notice_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(200) NOT NULL,
    content       TEXT         NOT NULL,
    pinned        BOOLEAN      NOT NULL DEFAULT FALSE,
    hidden        BOOLEAN      NOT NULL DEFAULT FALSE,
    publish_date  DATE         NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 이벤트. 관리자가 작성/수정하며 삭제는 없고 숨김 처리만 가능.
-- event_date: 이벤트가 실제로 열리는 날짜. publish_date: 이 게시글 자체가 공개되는 날짜(예약 게시).
CREATE TABLE IF NOT EXISTS event (
    event_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title         VARCHAR(200) NOT NULL,
    description   TEXT,
    location      VARCHAR(200),
    event_date    DATE         NOT NULL,
    pinned        BOOLEAN      NOT NULL DEFAULT FALSE,
    hidden        BOOLEAN      NOT NULL DEFAULT FALSE,
    publish_date  DATE         NOT NULL,
    created_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);
